name: Poll YouTube snapshots

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  poll:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions: { contents: read }
    env:
      DATABASE_POOL_URL: ${{ secrets.DATABASE_POOL_URL }}
      YT_API_KEY: ${{ secrets.YT_API_KEY }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 22, cache: 'npm' }
      - run: npm ci

      - name: Debug (manual only)
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "POOL URL len: ${#DATABASE_POOL_URL}"
          node -e "const u=process.env.DATABASE_POOL_URL||''; console.log('DB host:', (u.match(/@([^:/?]+)/)||[])[1]||'EMPTY');"

      - name: DB smoke test (pooler, no-verify)
        run: |
          node - <<'NODE'
          const { Pool } = require('pg');
          const url = process.env.DATABASE_POOL_URL;
          if (!url) { console.error('DATABASE_POOL_URL missing'); process.exit(1); }
          (async () => {
            try {
              const p = new Pool({ connectionString: url, ssl: { rejectUnauthorized: false } });
              const r = await p.query('select now()');
              console.log('DB now:', r.rows[0]);
              await p.end();
            } catch (e) { console.error(e); process.exit(1); }
          })();
          NODE

      - name: Run poller
        run: node poll.js
